version: '3.5'

services:
    apache_php:
        build: apache_php
        container_name: $APACHE_PHP_CONTAINER_NAME
        volumes:
            - ./config/vhosts:/etc/apache2/sites-enabled
            - ..:$APACHE_PHP_ROOT_DIR
        ports:
            - $APACHE_PHP_PORT:80
        depends_on:
            - rabbitmq
            - php_consume

    php_consume:
        build: php_consume
        container_name: $PHPCONSUME_CONTAINER_NAME
        volumes:
            - ..:$PHPCONSUME_ROOT_DIR
        depends_on:
            - rabbitmq

    maildev:
        image: djfarrelly/maildev
        container_name: $MAILDEV_CONTAINER_NAME
        ports:
            - 8001:80

    rabbitmq:
        image: rabbitmq:3.6-management
        container_name: $RABBITMQ_CONTAINER_NAME
        restart: always
        ports:
            - 8004:15672
            - 8005:5672
        environment:
            - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS

    db:
        image: mariadb/server:10.4
        container_name: $DB_CONTAINER_NAME
        environment:
            MARIADB_DATABASE: $DB_NAME
            MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MARIADB_USER: $DB_USER
            MARIADB_PASSWORD: $DB_PASSWORD
        ports:
            - $DB_PORT:3306
        volumes:
            - ./data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: $DB_ADMIN_CONTAINER_NAME
        environment:
            PMA_HOST: $DB_CONTAINER_NAME
            PMA_PORT: $DB_PORT
            PMA_USER: root
            PMA_PASSWORD: $DB_ROOT_PASSWORD
        ports:
            - 8080:80
        depends_on:
            - db

    mercure:
        image: dunglas/mercure
        container_name: $MERCURE_CONTAINER_NAME
        environment:
            JWT_KEY: aVerySecretKey
            ALLOW_ANONYMOUS: 1
            PUBLISH_ALLOWED_ORIGINS: '*'
            CORS_ALLOWED_ORIGINS: http://localhost
        ports:
            - 8003:80
